begin;
drop table if exists room_queue;
drop table if exists game_data;
drop table if exists game_history;
drop type if exists gameStatus;
drop type if exists playerTurn;
drop table if exists stats;
drop table if exists users;
drop table if exists schemaversion;
commit;