begin;
create table if not exists stats (
    id integer primary key generated by default as identity not null,
    userid integer references users(id) on delete cascade not null,
    wins integer default 0,
    losses integer default 0,
    draws integer default 0
);
commit;