begin;
create table if not exists game_history (
    id integer primary key generated by default as identity not null,
    player1 integer references users(id) on delete set null,
    player2 integer references users(id) on delete set null,
    turn boolean default false,
    -- ships position {PT: [A2, A3]}
    -- moves [A3, B4, C2, C3]
    datastring text not null
);
commit;