begin;
create table if not exists game_history (
    id integer primary key generated by default as identity not null,
    player1 integer references users(id) on delete set null,
    player2 integer references users(id) on delete set null default null,
    turn boolean default false,
    room_id text not null,
    next integer default null,
    -- ships position {PT: [A2, A3]}
    -- moves [A3, B4, C2, C3]
    datastring text default null
);
commit;