begin;
CREATE TYPE playerTurn AS ENUM (
    'player1',
    'player2'
);

CREATE TYPE gameStatus AS ENUM (
    'active',
    'complete'
);

create table if not exists game_history (
    id integer primary key generated by default as identity not null,
    player1 integer references users(id) on delete set null,
    player2 integer references users(id) on delete set null,
    turn playerTurn default 'player1',
    -- ships position {PT: [A2, A3]}
    -- moves [A3, B4, C2, C3]
    game_status gameStatus default 'active'
);
commit;