CREATE TABLE game_data (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  game_id INTEGER REFERENCES game_history(id) on delete cascade not null,
  player1_ships text,
  player2_ships text,
  player1_hits text,
  player1_misses text,
  player2_hits text,
  player2_misses text,
  winner text default null
);