CREATE TABLE game_data (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  game_id INTEGER REFERENCES game_history(id) on delete cascade not null,
  player1_ships text default null,
  player2_ships text default null,
  player1_hits text default null,
  player1_misses text default null,
  player2_hits text default null,
  player2_misses text default null,
  winner playerTurn default null,
  last_move timestamp default null
);