CREATE TABLE game_data (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  game_id INTEGER REFERENCES game_history(id) on delete cascade not null,
  player1_ships varchar(400) default null,
  player2_ships varchar(400) default null,
  player1_hits varchar(110) default null,
  player1_misses varchar(620) default null,
  player2_hits varchar(110) default null,
  player2_misses varchar(620) default null,
  winner playerTurn default null,
  last_move timestamp default null
);